services:
  web:
    container_name: varyshop_eu-sms-web
    image: varyshop/website:release-1.1.0
    command: 'python3 odoo-bin --addons-path="addons,varyshop,extra/sms/sms_modules" -r ${POSTGRES_USER-varyshop} -w ${POSTGRES_PASSWORD-varyshop} --db_host varyshop_eu-sms-db --db_port 5432 --limit-time-real=600 --limit-time-cpu=300'
    depends_on:
      - db
    ports:
      - ${WEB_HTTP_PORT:-8069}:8069
    volumes:
      - ./.config:/etc/odoo
      - ./.data:/root/.local/share/Odoo
      - ./sms_gateway:/app/extra/sms/sms_modules
      - ./vs_invoice_qr_payment:/app/varyshop/vs_invoice_qr_payment
    labels:
      createdBy: "bt_apps"
    environment:
      HOST: db
      USER: ${POSTGRES_USER-varyshop}
      DB_NAME: ${POSTGRES_DB:-postgres}
      PASSWORD: ${POSTGRES_PASSWORD-varyshop}
    networks:
      - proxy

  db:
    container_name: varyshop_eu-sms-db
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB-postgres}
      POSTGRES_USER: ${POSTGRES_USER-varyshop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-varyshop}
    volumes:
      - ./.data/.db:/var/lib/postgresql/data
    labels:
      createdBy: "bt_apps"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
